nodeLinker: node-modules

packageExtensions:
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  "@nuxt/typescript-build@*":
    peerDependencies:
      webpack: "*"
  "@portis/web3@*":
    peerDependencies:
      "@babel/core": "*"
  jest@*:
    peerDependencies:
      "@babel/core": "*"
  web3-provider-engine@*:
    peerDependencies:
      "@babel/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs
