name: "Deploy preview"

concurrency:
  group: deploy-pr-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
    inputs:
      network:
        type: string
        required: true
        default: "goerli"
        description: "target/env: mainnet, goerli, goerli-beta"
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }} || ${{ github.event.repository.full_name == github.repository }}
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2

      - name: "Enable yarn cache"
        uses: c-hive/gha-yarn-cache@v2  # using cache
        continue-on-error: true

      - name: "Setup node@16"
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: "Install dependencies"
        run: |
          yarn set version 3.1.1
          yarn install

      - name: "Lint check"
        run: |
          yarn lint --max-warnings 0

      - name: "Generate dist (default network: goerli)"
        run: yarn run ci:build:goerli

      - name: "Setup node@20"
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: "Deploy preview"
        uses: matter-labs/action-hosting-deploy@main
        id: deploy_preview
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZKSYNC_VUE }}"
          target: stage-mainnet
          projectId: zksync-vue
          channelId: 'version-${{ github.ref }}'

      - name: "Prepare /functions/"
        run: npm --prefix functions i

      - name: "Write Firebase service account (zksync-vue)"
        run: |
          node -e "require('fs').writeFileSync(process.env.RUNNER_TEMP + '/firebase-sa.json', process.env.FIREBASE_SERVICE_ACCOUNT)"
        env:
          FIREBASE_SERVICE_ACCOUNT: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZKSYNC_VUE }}"

      - name: "Deploy functions to firebase (staging)"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ runner.temp }}/firebase-sa.json"
        run: |
          npx firebase-tools@latest deploy --only functions --project zksync-vue --non-interactive
